### PR TITLE
Custom player

### PR DESCRIPTION
**Pull request by LivingWithHippos**
- added support for custom media player to use for "send to media player"
- added web video cast as media player

### CODE REVIEW

**Comment by Invictaz** [comment]
How does this functionality differ from the "open with" button that is already present @LivingWithHippos

**Comment by LivingWithHippos** [comment]
You manually choose what is opened (it will ignore system preferences) and it is opened directly to be played. In some cases the behaviour can be the same as with the "open with" button

**Comment by LivingWithHippos** [comment]
My use case was this: I don't like selecting "use always" when opening a media file, but I wanted a single button to open a player directly. You can remove the buttons inside the settings screen anyway

**Comment by Invictaz** [comment]
I never use the button "use always" only the 'use once'.

**Pull request merged**
